apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: envoy
  namespace: envoy-gateway
spec:
  interval: 30m0s
  chart:
    spec:
      chart: oci://docker.io/envoyproxy/gateway-helm
      version: "1.6.1"
      sourceRef:
        kind: HelmRepository
        name: envoy-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retires: 5
  values:
    replicaCount: 2
    service:
      type: LoadBalancer
