apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-charts
  namespace: flux-system
spec:
  type: "oci"
  interval: 5m0s
  url: oci://docker.io/envoyproxy/gateway-helm

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy
  namespace: envoy-gateway
spec:
  interval: 30m0s
  chart:
    spec:
      chart: gateway-helm
      version: "1.6.1"
      sourceRef:
        kind: HelmRepository
        name: envoy-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    replicaCount: 2
    service:
      type: LoadBalancer
